ALTER TABLE expenses ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS void_reason TEXT;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS voided_at TIMESTAMP;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS voided_by INTEGER REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_expenses_status ON expenses(status);

ALTER TABLE wastage_log ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
ALTER TABLE wastage_log ADD COLUMN IF NOT EXISTS void_reason TEXT;
ALTER TABLE wastage_log ADD COLUMN IF NOT EXISTS voided_at TIMESTAMP;
ALTER TABLE wastage_log ADD COLUMN IF NOT EXISTS voided_by INTEGER REFERENCES users(id) ON DELETE SET NULL;
