ALTER TABLE promotions ADD COLUMN IF NOT EXISTS offer_type TEXT DEFAULT 'discount';
ALTER TABLE promotions ADD COLUMN IF NOT EXISTS buy_quantity INTEGER DEFAULT 1;
ALTER TABLE promotions ADD COLUMN IF NOT EXISTS reward_quantity INTEGER DEFAULT 1;
ALTER TABLE promotions ADD COLUMN IF NOT EXISTS reward_discount_percent DOUBLE PRECISION DEFAULT 100;
ALTER TABLE promotions ADD COLUMN IF NOT EXISTS daily_start_time TEXT;
ALTER TABLE promotions ADD COLUMN IF NOT EXISTS daily_end_time TEXT;
ALTER TABLE promotions ADD COLUMN IF NOT EXISTS usage_limit INTEGER;
ALTER TABLE promotions ADD COLUMN IF NOT EXISTS per_customer_limit INTEGER;
ALTER TABLE promotions ADD COLUMN IF NOT EXISTS stackable INTEGER DEFAULT 0;
