'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import AdminLayout from '@/components/admin/admin-layout';
import { Download, Plus, Printer, RefreshCw, Search, X } from 'lucide-react';
import { apiJson } from '@/lib/authed-fetch';
import { nepalDateString } from '@/lib/report-dates';
import { useToast } from '@/components/ui/toast';
import { formatCalendarDate } from '@/lib/calendar-system.js';
import DateInput from '@/components/ui/date-input.jsx';
import { toCsv } from '@/lib/csv';

const money=n=>`Rs ${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const dateLabel=s=>formatCalendarDate(s);
/*
 * Nepal calendar, not the browser's. `localDate(new Date())` read the viewer's
 * clock, so on a UTC host anything after 18:15 UTC is already tomorrow in
 * Nepal and "Today" quietly queried the wrong day — while the deposits these
 * numbers roll up to are dated in Nepal. Same rule the reports engine uses.
 */
const nepalToday = () => nepalDateString();
const shiftNepalDate = (dateStr, days) => {
  const cursor = new Date(`${dateStr}T12:00:00+05:45`);
  cursor.setDate(cursor.getDate() + days);
  return nepalDateString(cursor);
};
function dates(range){
  const today = nepalToday();
  if (range === 'today') return { from: today, to: today };
  if (range === 'last7') return { from: shiftNepalDate(today, -6), to: today };
  if (range === 'all') return { from: '2000-01-01', to: '2999-12-31' };
  return { from: `${today.slice(0, 7)}-01`, to: today };
}

export default function SavingsPage(){
 const {addToast}=useToast(); const [data,setData]=useState(null);const [busy,setBusy]=useState(false);const [modal,setModal]=useState(false);
 const [filter,setFilter]=useState({search:'',type:'all',source:'all',status:'active',range:'today',page:1,pageSize:50});
 const [form,setForm]=useState({deposit_date:nepalDateString(),deposit_type:'bank',destination_name:'',source_account:'cash',amount:'',reference_number:'',notes:''});
 const query=useMemo(()=>{const r=dates(filter.range);return new URLSearchParams({...filter,from:r.from,to:r.to}).toString()},[filter]);
 const load=useCallback(async()=>{setBusy(true);try{setData(await apiJson(`/api/admin/savings?${query}`))}catch(e){addToast({type:'error',title:'Could not load savings',description:e.message})}finally{setBusy(false)}},[query,addToast]);
 useEffect(()=>{load()},[load]);
 const submit=async e=>{e.preventDefault();setBusy(true);try{await apiJson('/api/admin/savings',{method:'POST',body:JSON.stringify({...form,amount:Number(form.amount)})});setModal(false);setForm(f=>({...f,destination_name:'',amount:'',reference_number:'',notes:''}));addToast({type:'success',title:'Deposit recorded',description:'The transfer was posted to Savings & Deposits.'});await load()}catch(err){addToast({type:'error',title:'Could not record deposit',description:err.message})}finally{setBusy(false)}};
 const voidRow=async row=>{const reason=window.prompt(`Reason for voiding the ${money(row.amount)} deposit to ${row.destination_name}?`);if(!reason)return;try{await apiJson(`/api/admin/savings/${row.id}`,{method:'DELETE',body:JSON.stringify({reason})});await load()}catch(e){addToast({type:'error',title:'Could not void deposit',description:e.message})}};
 const exportCsv=()=>{const headers=['Date','Type','Destination','Source','Amount','Reference','Status','Notes'];const rows=(data?.rows||[]).map(r=>({Date:dateLabel(r.deposit_date),Type:r.deposit_type,Destination:r.destination_name,Source:r.source_account,Amount:money(r.amount),Reference:r.reference_number,Status:r.status,Notes:r.notes}));const url=URL.createObjectURL(new Blob([toCsv(headers,rows)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`savings-${nepalDateString()}.csv`;a.click();URL.revokeObjectURL(url)};
 const periods=data?.periods||{};
 return <AdminLayout><header className="print:hidden border-b border-gray-200 bg-white px-4 py-5 sm:px-6 lg:px-8"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold uppercase text-sky-700">Savings Transfer - Not an Expense</p><h1 className="mt-1 text-2xl font-bold text-gray-900">Savings & Deposits</h1><p className="mt-1 max-w-3xl text-sm text-gray-500">Bank and Sahakari deposits recorded across the restaurant. These are internal fund transfers, never operating expenses.</p></div><div className="flex gap-2"><button onClick={load} className={BTN}><RefreshCw className={`h-4 w-4 ${busy?'animate-spin':''}`}/>Refresh</button><button onClick={()=>setModal(true)} className={PRIMARY}><Plus className="h-4 w-4"/>Add Savings Deposit</button></div></div></header>
 <main className="space-y-5 bg-gray-50 p-4 sm:p-6 lg:p-8 print:bg-white print:p-0">
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Today',periods.today],['Last 3 Days',periods.last3],['Last 7 Days',periods.last7],['This Month',periods.month]].map(([label,p])=><div key={label} className="border border-gray-200 bg-white p-4"><div className="flex justify-between"><h2 className="text-sm font-bold text-gray-900">{label}</h2><span className="text-xs text-gray-500">{p?`${dateLabel(p.start)} - ${dateLabel(p.end)}`:'-'}</span></div><p className="mt-4 text-2xl font-bold text-gray-950">{money(p?.total)}</p><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><Stat label="From cash" value={money(p?.cash)}/><Stat label="From online" value={money(p?.online)}/><Stat label="Deposits" value={p?.count||0}/></div></div>)}</div>
  <div className="grid gap-3 sm:grid-cols-3"><Metric label="Net Cash in Hand" value={money(data?.balances?.cash)}/><Metric label="Net Online Balance" value={money(data?.balances?.online)}/><Metric label="Savings Balance" value={money(data?.balances?.savings)}/></div>
  <section className="border border-gray-200 bg-white"><div className="print:hidden border-b border-gray-200 p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-gray-400"/><input value={filter.search} onChange={e=>setFilter(f=>({...f,search:e.target.value,page:1}))} placeholder="Search bank, reference, notes" className={`${INPUT} pl-9`}/></label><Select label="Deposit type" value={filter.type} set={v=>setFilter(f=>({...f,type:v,page:1}))} options={[['all','All deposit types'],['bank','Bank'],['sahakari','Sahakari'],['fixed_deposit','Fixed deposit']]}/><Select label="Source account" value={filter.source} set={v=>setFilter(f=>({...f,source:v,page:1}))} options={[['all','All source accounts'],['cash','Cash'],['online','Online / bank']]}/><Select label="Status" value={filter.status} set={v=>setFilter(f=>({...f,status:v,page:1}))} options={[['active','Active'],['voided','Voided'],['all','All']]}/><Select label="Range" value={filter.range} set={v=>setFilter(f=>({...f,range:v,page:1}))} options={[['this_month','This Month'],['today','Today'],['last7','Last 7 Days'],['all','All Time']]}/></div></div>
   <div className="flex items-center justify-between border-b border-gray-200 px-4 py-3"><div><h2 className="text-sm font-bold text-gray-900">Savings Deposits</h2><p className="text-xs text-gray-500">{data?.pagination?.total||0} rows · Listed total {money(data?.listed_total)}</p></div><div className="print:hidden flex gap-2"><button onClick={exportCsv} className={ICON} title="Export CSV"><Download className="h-4 w-4"/></button><button onClick={()=>window.print()} className={ICON} title="Print"><Printer className="h-4 w-4"/></button></div></div>
   <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr>{['Date','Destination','Type','Source','Reference','Amount','Status',''].map(h=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{(data?.rows||[]).map(r=><tr key={r.id}><td className="whitespace-nowrap px-4 py-3">{r.deposit_date}</td><td className="px-4 py-3"><b>{r.destination_name}</b>{r.notes&&<p className="text-xs text-gray-500">{r.notes}</p>}</td><td className="px-4 py-3 capitalize">{r.deposit_type.replace('_',' ')}</td><td className="px-4 py-3 capitalize">{r.source_account}</td><td className="px-4 py-3 text-gray-500">{r.reference_number||'-'}</td><td className="px-4 py-3 font-bold tabular-nums">{money(r.amount)}</td><td className="px-4 py-3"><span className={`px-2 py-1 text-xs font-semibold ${r.status==='active'?'bg-emerald-50 text-emerald-700':'bg-gray-100 text-gray-500'}`}>{r.status}</span></td><td className="print:hidden px-4 py-3">{r.status==='active'&&<button onClick={()=>voidRow(r)} className="text-xs font-medium text-red-600 hover:underline">Void</button>}</td></tr>)}</tbody></table>{!data?.rows?.length&&<p className="py-16 text-center text-sm text-gray-500">No savings deposits in this range.</p>}</div>
   <div className="print:hidden flex items-center justify-between border-t border-gray-200 px-4 py-3 text-sm text-gray-600"><label>Rows <select value={filter.pageSize} onChange={e=>setFilter(f=>({...f,pageSize:Number(e.target.value),page:1}))} className="ml-2 border border-gray-300 px-2 py-1"><option>25</option><option>50</option><option>100</option></select></label><div className="flex items-center gap-3"><button disabled={filter.page<=1} onClick={()=>setFilter(f=>({...f,page:f.page-1}))} className={PAGE}>Previous</button><span>Page {data?.pagination?.page||1} of {data?.pagination?.pages||1}</span><button disabled={filter.page>=(data?.pagination?.pages||1)} onClick={()=>setFilter(f=>({...f,page:f.page+1}))} className={PAGE}>Next</button></div></div>
  </section>
 </main>
 {modal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form onSubmit={submit} className="w-full max-w-xl border border-gray-200 bg-white shadow-xl"><div className="flex items-center justify-between border-b border-gray-200 px-5 py-4"><div><h2 className="font-bold text-gray-900">Add Savings Deposit</h2><p className="text-xs text-gray-500">Records an internal transfer, not an expense.</p></div><button type="button" onClick={()=>setModal(false)} className={ICON}><X className="h-4 w-4"/></button></div><div className="grid gap-4 p-5 sm:grid-cols-2"><Field label="Deposit date"><DateInput required value={form.deposit_date} onChange={deposit_date=>setForm({...form,deposit_date})} className={INPUT}/></Field><Field label="Deposit type"><select value={form.deposit_type} onChange={e=>setForm({...form,deposit_type:e.target.value})} className={INPUT}><option value="bank">Bank</option><option value="sahakari">Sahakari</option><option value="fixed_deposit">Fixed deposit</option></select></Field><Field label="Bank / Sahakari name"><input required value={form.destination_name} onChange={e=>setForm({...form,destination_name:e.target.value})} className={INPUT}/></Field><Field label="Source account"><select value={form.source_account} onChange={e=>setForm({...form,source_account:e.target.value})} className={INPUT}><option value="cash">Cash in hand</option><option value="online">Online / bank</option></select></Field><Field label="Amount"><input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} className={INPUT}/></Field><Field label="Reference"><input value={form.reference_number} onChange={e=>setForm({...form,reference_number:e.target.value})} className={INPUT}/></Field><Field label="Notes" wide><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="min-h-20 w-full border border-gray-300 p-3 text-sm"/></Field></div><div className="flex justify-end gap-2 border-t border-gray-200 px-5 py-4"><button type="button" onClick={()=>setModal(false)} className={BTN}>Cancel</button><button disabled={busy} className={PRIMARY}>{busy?'Saving...':'Record Deposit'}</button></div></form></div>}
 </AdminLayout>
}

function Stat({label,value}){return <div><p className="text-gray-500">{label}</p><p className="mt-1 font-semibold text-gray-900">{value}</p></div>};function Metric({label,value}){return <div className="border border-gray-200 bg-white p-4"><p className="text-xs text-gray-500">{label}</p><p className="mt-2 text-xl font-bold text-gray-900">{value}</p></div>};
function Select({label,value,set,options}){return <label className="text-xs font-medium text-gray-600">{label}<select value={value} onChange={e=>set(e.target.value)} className={`${INPUT} mt-1`}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>};function Field({label,wide,children}){return <label className={`text-sm font-medium text-gray-700 ${wide?'sm:col-span-2':''}`}>{label}<div className="mt-1">{children}</div></label>}
const BTN='inline-flex h-10 items-center justify-center gap-2 border border-gray-300 bg-white px-4 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50';
const PRIMARY='inline-flex h-10 items-center justify-center gap-2 rounded-none border border-gray-950 bg-gray-950 px-4 text-sm font-semibold text-white hover:bg-black disabled:opacity-50 [color:#fff!important]';
const ICON='inline-flex h-9 w-9 items-center justify-center border border-gray-300 text-gray-600 hover:bg-gray-50';
const INPUT='h-10 w-full border border-gray-300 bg-white px-3 text-sm text-gray-900';
const PAGE='border border-gray-300 px-3 py-1.5 disabled:opacity-40';
